### ISSUE TITLE
Unable to vote on minecraft.global

### ISSUE THREAD

**Issue by rpetersen27** [DrexHD/Fabric-Votifier#12]
I have 6 sites correctly configured and it works like a charm. But on minecraft.global it fails. Server shows following error message

```
[22:07:18] [Thread-1/ERROR]: Unable to decrypt vote record. Make sure that that your public key
 [22:07:18] [Thread-1/ERROR]: matches the one you gave the server list.
 javax.crypto.BadPaddingException: Decryption error
         at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:369) ~[?:?]
         at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:282) ~[?:?]
         at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:372) ~[?:?]
         at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:406) ~[?:?]
         at javax.crypto.Cipher.doFinal(Cipher.java:2205) ~[?:?]
         at me.drex.votifier.rsa.RSA.decrypt(RSA.java:45) ~[fabric-votifier-1.1.4.jar:?]
         at me.drex.votifier.VoteReceiver.run(VoteReceiver.java:83) [fabric-votifier-1.1.4.jar:?]
```

I triple checked, and the public key is the same as for all the other vote sites. Might also be an issue on their site, but I am unfortunately not able to debug this atm.

**Comment by DrexHD** [comment]
I don't know what would cause that, other than they would be using some kind of different system for voting. I don't think I can help on this one ):
